FROM java:8

LABEL maintainer="kjh9267z@naver.com"

EXPOSE 8082

ARG JAR_FILE=target/post-service-0.0.1-SNAPSHOT.jar

ADD ${JAR_FILE} post-service.jar

ENTRYPOINT ["java", "-jar", "/post-service.jar"]
