FROM java:8

LABEL maintainer="kjh9267z@naver.com"

EXPOSE 8081

ARG JAR_FILE=target/home-service-0.0.1-SNAPSHOT.jar

ADD ${JAR_FILE} home-service.jar

ENTRYPOINT ["java", "-jar", "/home-service.jar"]
